# This is a basic example of how to instantiate a vSRX 3.0 with an embedded
# configuration in Contrail using OpenStack Heat. It creates the necessary flavor
# as well as a management network. The only thing that must be present before
# executing this template is the image, which is provided via the vsrx_image
# parameter.
#
# The three properties used to embed the configuration are: config_drive (set to
# true), user_data_format (set to raw), and user_data.
#
# The root password in the embedded configuration is jnpr123
#
# Example of image creation:
# glance image-create --name vsrx3-18.4R1 --visibility public --container-format bare --disk-format qcow2 --file junos-vsrx3-x86-64-18.4R1.8.qcow2
#
# Tested with vSRX 3.0 18.4R1 on Contrail Networking 5.0.3 with Kolla OpenStack Queens.

heat_template_version: queens

parameters:
    vsrx_image:
        type: string

resources:
    vsrx_vm:
        type: OS::Nova::Server
        properties:
            name: "basic-vsrx3"
            flavor: { get_resource: vsrx_flavor }
            image: { get_param: vsrx_image }
            networks:
            - network: {get_resource: vsrx_mgmt}
            config_drive: true
            user_data_format: RAW
            user_data: |
                #junos-config
                system {
                    host-name testing;
                    root-authentication {
                        encrypted-password "$5$VBuEwCjU$vqZ80sGmEQNvjS4cJQ3O2b7p/nNzNTTmUgOYVCj1b6/";
                    }
                    services {
                        ssh;
                        web-management {
                            http {
                                interface fxp0.0;
                            }
                        }
                    }
                    syslog {
                        user * {
                            any emergency;
                        }
                        file messages {
                            any any;
                            authorization info;
                        }
                        file interactive-commands {
                            interactive-commands any;
                        }
                    }
                    license {
                        autoupdate {
                            url https://ae1.juniper.net/junos/key_retrieval;
                        }
                    }
                }
                security {
                    log {
                        mode stream;
                        report;
                    }
                }
                interfaces {
                    fxp0 {
                        unit 0 {
                            family inet {
                                dhcp;
                            }
                        }
                    }
                }


    vsrx_ipam:
        type: OS::ContrailV2::NetworkIpam
        properties:
            name: "basic-vsrx3-ipam"

    vsrx_mgmt:
        type: OS::ContrailV2::VirtualNetwork
        properties:
            name: "basic-vsrx3-mgmt-vn"
            network_ipam_refs: [{get_resource: vsrx_ipam}]
            network_ipam_refs_data:
            - network_ipam_refs_data_ipam_subnets:
                - network_ipam_refs_data_ipam_subnets_addr_from_start: true
                  network_ipam_refs_data_ipam_subnets_subnet: { network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: "10.0.0.0",
                    network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: "24"}

    vsrx_flavor:
        type: OS::Nova::Flavor
        properties:
            name: "basic-vsrx3-flavor"
            ram: 4096
            vcpus: 2
            disk: 20
